# 阿里云OSS配置
alioss:
  endpoint: oss-cn-beijing.aliyuncs.com  # 第1项配置：要带上 https:// ,上传时要使用的
  accessKeyId: LTAI5tJa9gErSLEVv1wsbxvN       # 第2项配置  根据自己的帐号配置
  accessKeySecret: oUL3aCbzf5p75T2CPSlPAqgvbe91bu   # 第3项配置  根据自己的帐号配置
  bucketName: concert-p        # 第4项配置  存储空间名称
  urlPrefix: https://concert-p.oss-cn-beijing.aliyuncs.com/ # 第5项配置  Bucket域名，访问文件时作为URL前缀，注意要加上 https:// 和 结尾带上 /
open-feign:
  user:
    api-url: http://127.0.0.1:28001
  seat:
    api-url: http://127.0.0.1:28003
  concert:
    api-url: http://127.0.0.1:28003
  order:
    api-url: http://127.0.0.1:28004
  business:
    api-url: http://127.0.0.1:28002

spring:
  data:
    redis:
      host: 121.43.96.182
      password: 123456
      timeout: 5000
      database: 0
      port: 15112
#spring:
#  data:
#    redis:
#      host: toastfish3.rwlb.rds.aliyuncs.com
#      username: concert_redis
#      password: Concert123
#      timeout: 5000
#      database: 0
#      port: 15112
logging:
  level:
    org:
      springframework:
        data:
          redis:
            core:
              RedisTemplate: DEBUG
            cache:
              RedisCacheManager: DEBUG

