server:
  port: 28010 #网关端口
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes: #网关路由配置
        - id: business #路由id，自定义，只要唯一
          uri: http://127.0.0.1:28002
          predicates: # 路由断言，也就是判断请求是否符合路由规则的条件
            - Path=/business/** # 这个是按照路径匹配，只要以/user/开头就符合要求