server:
  port: 28010 #网关端口
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes: #网关路由配置
        - id: users #路由id，自定义，只要唯一
          uri: http://127.0.0.1:28001
          predicates: # 路由断言，也就是判断请求是否符合路由规则的条件
            - Path=/users/** # 这个是按照路径匹配，只要以/user/开头就符合要求
        - id: business
          uri: http://127.0.0.1:28002
          predicates:
            - Path=/business/**
        - id: concert
          uri: http://127.0.0.1:28003
          predicates:
            - Path=/concert/**
        - id: order
          uri: http://127.0.0.1:28004
          predicates:
            - Path=/order/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
            allowed-headers:
              - "*"
            exposed-headers:
              - "Authorization"
            allowCredentials: true
            max-age: 3600